---
- hosts: devsecops_mgmt_jenkins_master_eip
  become: true
  name: Set up Jenkins
  # TODO: Vars are not being read automatically via hosts, so declaring them manually. Shouldn't have to do this. Jenkins-specific vars do not belong in /group_vars/all since this repo is for more than just Jenkins.
  vars_files:
    - ../group_vars/devsecops_mgmt_jenkins_master_eip/vars.yml
    - ../group_vars/devsecops_mgmt_jenkins_master_eip/vault.yml
  pre_tasks:
    - set_fact:
        jenkins_external_hostname: "{{ inventory_hostname }}"
  roles:
    - gsa.jenkins
  tasks:

    - name: Set YUM repos for AWSCLI
      yum_repository:
        name: rhui-REGION-rhel-server-optional
        description: rhel optional rpms
        enabled: yes
        mirrorlist: https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/$releasever/$basearch/optional/os

    - name: Install AWSCLI
      yum:
        name: awscli
    
    - name: Install jenkins_job dependencies
      yum:
        name: python-lxml

    - name: Set up pipeline
      jenkins_job:
        config: "{{ lookup('file', 'files/job.xml') }}"
        name: test-auto
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
    - name: Backup job
      jenkins_job:
        config: "{{ lookup('file', '../../jenkins-jobs/jenkins-backup/job.xml') }}"
        name: jenkins-master-backup
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"